name: cupertino_controllers
description: A Flutter plugin with Cupertino Controller Examples. This includes a Table View Controller, Master Detail Controller, Cupertino Cell with Xcode Storyboard templates (basic detail, subtitle...), and detail examples
version: 0.1.1
author: Rhodes Davis Jr. <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/plugins/tree/master/packages/cupertino_controllers

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0-nullsafety.0
  flutter_sticky_header: ^0.5.0

flutter:
