name: cupertino_controllers
description: A Flutter plugin with Cupertino Controller Examples. This includes a Table View Controller, Master Detail Controller, Cupertino Cell with Xcode Storyboard templates (basic detail, subtitle...), and detail examples
version: 1.0.2-nullsafety
author: Rhodes Davis Jr. <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/plugins

environment:
  sdk: '>=2.12.0-259.8.beta < 3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0-nullsafety.0
  flutter_sticky_header: ^0.5.0

flutter:
